<a href="https://colab.research.google.com/github/stormjao/pythonprojetons/blob/main/curso_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Analise de Dados**

In [ ]:
#Importando Bibliotecas e arquivos
import os
import pandas as pd
import plotly.express as px
lista_arquivos = os.listdir("/content/drive/MyDrive/pythom/Vendas")
display(lista_arquivos)

['Vendas - Fortaleza.csv',
 'Vendas - Goiás.csv',
 'Vendas - São Paulo.csv',
 'Vendas - Belo Horizonte.csv',
 'Devolucoes - Rio de Janeiro.csv',
 'Devolucoes - Salvador.csv',
 'Devolucoes - Fortaleza.csv',
 'Devolucoes - Goiás.csv',
 'Vendas - Salvador.csv',
 'Vendas - Rio de Janeiro.csv',
 'Devolucoes - São Paulo.csv',
 'Devolucoes - Porto Alegre.csv',
 'Devolucoes - Belo Horizonte.csv',
 'Vendas - Recife.csv',
 'Vendas - Porto Alegre.csv',
 'Vendas - Curitiba.csv',
 'Devolucoes - Recife.csv',
 'Devolucoes - Curitiba.csv']

In [ ]:
#Tabelas de formas organizadas com todas em 1 só 

tabela_total = pd.DataFrame()

for arquivo in lista_arquivos:
  if "Vendas" in arquivo:
   tabela = pd.read_csv(f"/content/drive/MyDrive/pythom/Vendas/{arquivo}")
   tabela_total = tabela_total.append(tabela)
display(tabela_total)

,Unnamed: 0,SKU,Produto,Quantidade Vendida,Primeiro Nome,Sobrenome,Data,Loja,Preco Unitario,Unnamed: 8
0,2,HL1148,Câmera,2,Camila,Sobral,10/21/2018,Fortaleza,2100,NaN
1,3,HL1918,iPhone,3,Clara,Bruno,7/8/2018,Fortaleza,5300,NaN
2,4,HL9962,Android,4,Eduardo,Pacheco,12/19/2018,Fortaleza,3400,NaN
3,11,HL1918,iPhone,2,Rafael,Rocha,12/22/2018,Fortaleza,5300,NaN
4,15,HL2714,Tablet,2,Caio,Ferreira,7/26/2018,Fortaleza,1600,NaN
...,...,...,...,...,...,...,...,...,...,...
714,9859,HL2714,Tablet,1,Júlio,Fraga,12/25/2018,Curitiba,1600,NaN
715,9876,HL4379,Televisão,5,Bruno,Mota,4/30/2018,Curitiba,2500,NaN
716,9918,HL1148,Câmera,2,Lucas,Reis,12/27/2018,Curitiba,2100,NaN
717,9944,HL1918,iPhone,5,Raphael,Kurtz,7/16/2018,Curitiba,5300,NaN
718,9998,HL7348,SmartWatch,1,Vinícius,Antunes,12/10/2018,Curitiba,1400,NaN

In [ ]:
#Tabela Quantidade Vendida
tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[["Quantidade Vendida"]].sort_values(by="Quantidade Vendida", ascending=False)
display(tabela_produtos)

            Quantidade Vendida
Produto
iPhone                    8974
Televisão                 5931
Notebook                  3249
Android                   3183
SmartWatch                2980
Tablet                    2921
Câmera                    2805

In [ ]:
#Tabela Faturamento
tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']

tabela_faturamento = tabela_total.groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[["Faturamento"]].sort_values(by="Faturamento", ascending=False)

display(tabela_faturamento)

            Faturamento
Produto
iPhone         47562200
Televisão      14827500
Notebook       11371500
Android        10822200
Câmera          5890500
Tablet          4673600
SmartWatch      4172000

In [ ]:
#Loja com maiores Faturamentos
tabela_lojas = tabela_total.groupby('Loja').sum()
tabela_lojas = tabela_lojas[['Faturamento']].sort_values(by="Faturamento", ascending=False)
display(tabela_lojas)

                Faturamento
Loja
São Paulo          22098300
Rio de Janeiro     14867800
Fortaleza          14087900
Salvador           13111300
Goiás               7441800
Recife              7303000
Curitiba            7060500
Porto Alegre        6868600
Belo Horizonte      6480300

In [ ]:
#Criar Dashboard

grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show()